/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "game.h"
/* Header for class com_learnz_game_act_GameLibJNIWrapper */

#ifndef _Included_com_learnz_game_act_GameLibJNIWrapper
#define _Included_com_learnz_game_act_GameLibJNIWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_learnz_game_act_GameLibJNIWrapper
 * Method:    on_surface_created
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_learnz_game_act_GameLibJNIWrapper_on_1surface_1created
  (JNIEnv * env, jclass class){
	on_surface_created();
}

/*
 * Class:     com_learnz_game_act_GameLibJNIWrapper
 * Method:    on_surface_changed
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_learnz_game_act_GameLibJNIWrapper_on_1surface_1changed
  (JNIEnv * env, jclass class, jint jint1, jint jint2){
	on_surface_changed();
}

/*
 * Class:     com_learnz_game_act_GameLibJNIWrapper
 * Method:    on_draw_frame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_learnz_game_act_GameLibJNIWrapper_on_1draw_1frame
  (JNIEnv * env, jclass class){
	on_draw_frame();
}

#ifdef __cplusplus
}
#endif
#endif
